#!/usr/bin/env python3
"""
AQARION SV-001-V2 deterministic reference verifier.

Contract:
    n = m*k
    K[x, (x+s) mod n] = 1
    P = equal-block averaging projection
    D = (I-P) K P
    U = normalized block-indicator isometry
    G = U^T D^T D U

Target:
    G = alpha_sq * (2I - S - S^T)

where:
    r = s mod k
    alpha_sq = r(k-r)/k^2

This verifier is intentionally deterministic and fail-closed.
"""

import argparse
import json
import math
import sys

import numpy as np


CONTRACT = "SV-001-V2"
RECEIPT_SCHEMA = "aqarion.sv001.verifier-result.v2"

M_MIN = 2
M_MAX = 8
K_MIN = 2
K_MAX = 8

ABS_TOL = 1.0e-12


def expected_case_count(
    m_min: int,
    m_max: int,
    k_min: int,
    k_max: int,
) -> int:
    """
    Exact number of cases generated by:

        m_min <= m <= m_max
        k_min <= k <= k_max
        1 <= s < m*k
    """
    total = 0
    for m in range(m_min, m_max + 1):
        for k in range(k_min, k_max + 1):
            total += m * k - 1
    return total


def build_koopman(m: int, k: int, s: int) -> np.ndarray:
    n = m * k
    K = np.zeros((n, n), dtype=np.float64)

    for x in range(n):
        K[x, (x + s) % n] = 1.0

    return K


def build_block_projection(m: int, k: int) -> np.ndarray:
    n = m * k
    P = np.zeros((n, n), dtype=np.float64)

    for block in range(m):
        indices = list(range(block * k, (block + 1) * k))
        P[np.ix_(indices, indices)] = 1.0 / k

    return P


def build_block_isometry(m: int, k: int) -> np.ndarray:
    n = m * k
    U = np.zeros((n, m), dtype=np.float64)

    for block in range(m):
        U[block * k:(block + 1) * k, block] = 1.0 / math.sqrt(k)

    return U


def build_cycle_laplacian(m: int) -> np.ndarray:
    """
    L = 2I - S - S^T.

    For m=2 this naturally gives the doubled-edge form because
    S = S^T.
    """
    S = np.zeros((m, m), dtype=np.float64)

    for i in range(m):
        S[i, (i + 1) % m] = 1.0

    return 2.0 * np.eye(m, dtype=np.float64) - S - S.T


def alpha_sq_from_shift(k: int, s: int) -> float:
    r = s % k
    return (r * (k - r)) / float(k * k)


def expected_operator_norm(m: int, alpha_sq: float) -> float:
    alpha = math.sqrt(alpha_sq)

    if m % 2 == 0:
        return 2.0 * alpha

    return 2.0 * alpha * math.cos(math.pi / (2.0 * m))


def evaluate_case(m: int, k: int, s: int) -> dict:
    n = m * k

    K = build_koopman(m, k, s)
    P = build_block_projection(m, k)
    U = build_block_isometry(m, k)

    I = np.eye(n, dtype=np.float64)

    D = (I - P) @ K @ P

    G_observed = U.T @ D.T @ D @ U

    alpha_sq = alpha_sq_from_shift(k, s)
    L_cycle = build_cycle_laplacian(m)

    G_expected = alpha_sq * L_cycle

    if not np.all(np.isfinite(D)):
        return {
            "finite": False,
            "gram_error": math.inf,
            "norm_error": math.inf,
            "r": s % k,
        }

    if not np.all(np.isfinite(G_observed)):
        return {
            "finite": False,
            "gram_error": math.inf,
            "norm_error": math.inf,
            "r": s % k,
        }

    gram_error = float(
        np.max(np.abs(G_observed - G_expected))
    )

    singular_values = np.linalg.svd(
        D,
        compute_uv=False,
    )

    observed_norm = float(np.max(singular_values))
    target_norm = expected_operator_norm(m, alpha_sq)

    norm_error = abs(observed_norm - target_norm)

    return {
        "finite": math.isfinite(gram_error)
        and math.isfinite(norm_error),
        "gram_error": gram_error,
        "norm_error": norm_error,
        "r": s % k,
    }


def evaluate_sv001() -> dict:
    expected_cases = expected_case_count(
        M_MIN,
        M_MAX,
        K_MIN,
        K_MAX,
    )

    cases_executed = 0
    zero_r_cases = 0
    nonzero_r_cases = 0

    gram_failures = 0
    norm_failures = 0
    nonfinite_failures = 0

    max_gram_error = 0.0
    max_norm_error = 0.0

    worst_gram_case = None
    worst_norm_case = None

    for m in range(M_MIN, M_MAX + 1):
        for k in range(K_MIN, K_MAX + 1):
            for s in range(1, m * k):
                cases_executed += 1

                result = evaluate_case(m, k, s)

                r = result["r"]

                if r == 0:
                    zero_r_cases += 1
                else:
                    nonzero_r_cases += 1

                if not result["finite"]:
                    nonfinite_failures += 1
                    continue

                gram_error = result["gram_error"]
                norm_error = result["norm_error"]

                if gram_error > max_gram_error:
                    max_gram_error = gram_error
                    worst_gram_case = {
                        "m": m,
                        "k": k,
                        "s": s,
                        "error": gram_error,
                    }

                if norm_error > max_norm_error:
                    max_norm_error = norm_error
                    worst_norm_case = {
                        "m": m,
                        "k": k,
                        "s": s,
                        "error": norm_error,
                    }

                if gram_error > ABS_TOL:
                    gram_failures += 1

                if norm_error > ABS_TOL:
                    norm_failures += 1

    case_count_matches_domain = (
        cases_executed == expected_cases
    )

    partition_matches_total = (
        zero_r_cases + nonzero_r_cases
        == cases_executed
    )

    status = (
        "PASS"
        if (
            case_count_matches_domain
            and partition_matches_total
            and gram_failures == 0
            and norm_failures == 0
            and nonfinite_failures == 0
        )
        else "FAIL"
    )

    return {
        "receipt_schema": RECEIPT_SCHEMA,
        "contract": CONTRACT,

        "operator_convention":
            "K[x,(x+s) mod n]=1; "
            "D=(I-P)K_sP; "
            "G=U^T D^T D U",

        "target":
            "G=(r(k-r)/k^2)(2I-S-S^T)",

        "domain": {
            "m_min": M_MIN,
            "m_max": M_MAX,
            "k_min": K_MIN,
            "k_max": K_MAX,
            "shift_rule": "1 <= s < m*k",
        },

        "result": {
            "status": status,
            "cases_executed": cases_executed,
            "zero_r_cases": zero_r_cases,
            "nonzero_r_cases": nonzero_r_cases,
            "gram_failures": gram_failures,
            "norm_failures": norm_failures,
            "nonfinite_failures": nonfinite_failures,
            "max_gram_error": max_gram_error,
            "max_norm_error": max_norm_error,
            "worst_gram_case": worst_gram_case,
            "worst_norm_case": worst_norm_case,
        },

        "consistency": {
            "expected_cases_from_domain":
                expected_cases,

            "case_count_matches_domain":
                case_count_matches_domain,

            "r_partition_matches_total":
                partition_matches_total,

            "status_matches_failure_counts":
                (
                    status == "PASS"
                    if (
                        case_count_matches_domain
                        and partition_matches_total
                        and gram_failures == 0
                        and norm_failures == 0
                        and nonfinite_failures == 0
                    )
                    else status == "FAIL"
                ),
        },

        "tolerance": {
            "absolute": ABS_TOL,
            "dynamic_relaxation": False,
        },
    }


def main() -> int:
    parser = argparse.ArgumentParser()

    parser.add_argument(
        "--json-output",
        type=str,
        help="Path for deterministic JSON receipt.",
    )

    args = parser.parse_args()

    result = evaluate_sv001()

    if args.json_output:
        with open(
            args.json_output,
            "w",
            encoding="utf-8",
        ) as handle:
            json.dump(
                result,
                handle,
                indent=2,
                allow_nan=False,
            )

    data = result["result"]

    print(
        f"total={data['cases_executed']}"
    )

    print(
        "expected_total="
        f"{result['consistency']['expected_cases_from_domain']}"
    )

    print(
        "Gram max err "
        f"{data['max_gram_error']:.6e}"
    )

    print(
        "Op-norm max err "
        f"{data['max_norm_error']:.6e}"
    )

    print(
        f"status={data['status']}"
    )

    return (
        0
        if data["status"] == "PASS"
        else 1
    )


if __name__ == "__main__":
    sys.exit(main())
