import Mathlib.Data.Setoid.Basic
import Mathlib.Data.Fintype.Card
import Mathlib.Logic.Relation

namespace Aqarion

universe u

variable {α : Type u}

/-
  P0 / T10
  ----------
  Unary dynamics on equivalence relations.

  No matrices.
  No finite partitions.
  No graph layer.
  No Koopman layer yet.

  The foundational object is Setoid.
-/

/-- Transport an equivalence relation through a unary map. -/
def dynImage (T : α → α) (P : Setoid α) : Setoid α :=
  P.map T

/-- One deterministic repair step. -/
def dynStep (T : α → α) (P : Setoid α) : Setoid α :=
  P ⊔ dynImage T P

/-- Unary congruence / deterministic invariance. -/
def TInvariant (T : α → α) (P : Setoid α) : Prop :=
  ∀ ⦃x y : α⦄, P x y → P (T x) (T y)

/--
The image relation generated by `P` is contained in `P`
iff `P` is invariant under `T`.
-/
theorem invariant_iff_map_le
    (T : α → α) (P : Setoid α) :
    TInvariant T P ↔ dynImage T P ≤ P := by
  sorry

/--
A partition is already repaired exactly when one repair step
does nothing.
-/
theorem invariant_iff_fixed
    (T : α → α) (P : Setoid α) :
    TInvariant T P ↔ dynStep T P = P := by
  sorry

/--
The one-step repair is extensive.
-/
theorem dynStep_extensive
    (T : α → α) (P : Setoid α) :
    P ≤ dynStep T P := by
  sorry

/--
The one-step repair is monotone.
-/
theorem dynStep_mono
    (T : α → α) :
    Monotone (dynStep T) := by
  sorry

/--
Transport through a join distributes over joins.
-/
theorem dynImage_sup
    (T : α → α) (P Q : Setoid α) :
    dynImage T (P ⊔ Q)
      = dynImage T P ⊔ dynImage T Q := by
  sorry

/--
Therefore one deterministic repair step preserves joins.
-/
theorem dynStep_sup
    (T : α → α) (P Q : Setoid α) :
    dynStep T (P ⊔ Q)
      = dynStep T P ⊔ dynStep T Q := by
  sorry

end Aqarion
